{
 "title": "Cisco UCS",
 "description": "Metrics pulled from each UCS domain by the ucs-exporter.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Cluster", "query": "prometheus" },
   {
    "name": "domain",
    "query": {
     "query": "label_values(ucs_vnic_stats_rx, domain)"
    }
   },
   {
    "name": "rack",
    "query": {
     "query": "label_values(ucs_vnic_stats_rx, rack)"
    }
   },
   {
    "name": "chassis",
    "query": {
     "query": "label_values(ucs_vnic_stats_rx, chassis)"
    }
   },
   {
    "name": "blade",
    "query": {
     "query": "label_values(ucs_vnic_stats_rx, blade)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Faults", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Critical Faults",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (domain, severity, type) (ucs_faults_total{domain=~\"${domain}\",severity=~\"critical\",type=\"management\"})",
     "legendFormat": "{{domain}} {{severity}} {{type}}"
    }
   ]
  },
  {
   "title": "Major Faults",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (domain, severity, type) (ucs_faults_total{domain=~\"${domain}\",severity=~\"major\",type=\"management\"})",
     "legendFormat": "{{domain}} {{severity}} {{type}}"
    }
   ]
  },
  {
   "title": "Minor Faults",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (domain, severity, type) (ucs_faults_total{domain=~\"${domain}\",severity=~\"minor\",type=\"management\"})",
     "legendFormat": "{{domain}} {{severity}} {{type}}"
    }
   ]
  },
  {
   "title": "Warning Faults",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (domain, severity, type) (ucs_faults_total{domain=~\"${domain}\",severity=~\"warning\",type=\"management\"})",
     "legendFormat": "{{domain}} {{severity}} {{type}}"
    }
   ]
  },
  {
   "title": "Faults",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum by (severity) (ucs_faults_total{domain=~\"${domain}\",severity=~\"critical|major|minor|warning\",type=\"management\"})",
     "legendFormat": "{{domain}} {{severity}} {{type}}"
    }
   ]
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Blade slots usage (percent)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (domain, class) (ucs_slots_equipped{domain=~\"${domain}\"}) / sum by (domain, class) (ucs_slots_total{domain=~\"${domain}\"})) * 100",
     "legendFormat": "{{domain}}"
    },
    {
     "expr": "(sum by (class) (ucs_slots_equipped) / sum by (class) (ucs_slots_total)) * 100",
     "legendFormat": "All domains"
    }
   ]
  },
  {
   "title": "CPU cores count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by (domain, class) (ucs_cpu_cores_total{domain=~\"${domain}\"})",
     "legendFormat": "{{domain}} {{class}} cores"
    }
   ]
  },
  {
   "title": "Memory available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by (domain, class) (ucs_mem_total{domain=~\"${domain}\"})",
     "legendFormat": "{{domain}} {{class}}s total ram"
    },
    {
     "expr": "sum by (domain, class) (ucs_mem_available_total{domain=~\"${domain}\"})",
     "legendFormat": "{{domain}} {{class}}s available ram"
    }
   ]
  },
  {
   "title": "Server count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (domain, class) (ucs_servers_total{domain=~\"${domain}\"})",
     "legendFormat": "{{domain}} {{class}}s"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Ethernet bytes received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (domain, pc_label, pc_name) (rate(ucs_ether_stats_bytes_rx{domain=~\"${domain}\"}[10m]))",
     "legendFormat": "{{domain}} {{pc_label}} {{pc_name}}"
    }
   ]
  },
  {
   "title": "Ethernet bytes transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (domain, pc_label, pc_name) (rate(ucs_ether_stats_bytes_tx{domain=~\"${domain}\"}[10m]))",
     "legendFormat": "{{domain}} {{pc_label}} {{pc_name}}"
    }
   ]
  },
  {
   "title": "HBA Statistics for VNIC in Packets Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (domain, rack, chassis, blade) (rate(ucs_vnic_stats_packets_rx{domain=~\"${domain}\",chassis=~\"${chassis}\",rack=~\"${rack}\",blade=~\"${blade}\"}[10m]))",
     "legendFormat": "{{domain}}  {{rack}} {{chassis}} {{blade}}"
    }
   ]
  },
  {
   "title": "HBA Statistics for VNIC in Packets Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (domain, rack, chassis, blade) (rate(ucs_vnic_stats_packets_tx{domain=~\"${domain}\",chassis=~\"${chassis}\",rack=~\"${rack}\",blade=~\"${blade}\"}[10m]))",
     "legendFormat": "{{domain}}  {{rack}} {{chassis}} {{blade}}"
    }
   ]
  },
  { "title": "Temperature / Fan speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (domain, chassis, rack, blade) (max_over_time(ucs_server_temperature{domain=~\"${domain}\",chassis=~\"${chassis}\",rack=~\"${rack}\",blade=~\"${blade}\"}[10m]))",
     "legendFormat": "{{domain}} {{chassis}} {{rack}} {{blade}}"
    }
   ]
  },
  {
   "title": "Fan speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "max by (domain, chassis) (avg_over_time(ucs_fan_speed{domain=~\"${domain}\",chassis=~\"${chassis}\"}[10m]))",
     "legendFormat": "{{domain}} {{chassis}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (domain, chassis, rack, blade) (ucs_server_temperature{domain=~\"${domain}\",chassis=~\"${chassis}\",rack=~\"${rack}\",blade=~\"${blade}\"})",
     "legendFormat": "{{domain}} {{chassis}} {{rack}} {{blade}}"
    }
   ]
  },
  { "title": "System software", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "User CPU load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (domain, switch) (avg_over_time(ucs_cpu_load{domain=~\"${domain}\"}[10m]))",
     "legendFormat": "{{domain}} {{switch}}"
    }
   ]
  },
  {
   "title": "Kernel Memory Usage Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 * avg by (domain, switch) (avg_over_time(ucs_kernel_mem_free{domain=~\"${domain}\"}[10m])) / avg by (domain, switch) (avg_over_time(ucs_kernel_mem_total[10m])))",
     "legendFormat": "{{domain }} {{switch}}"
    }
   ]
  },
  {
   "title": "Memory available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by (domain, switch) (avg_over_time(ucs_mem_available{domain=~\"${domain}\"}[10m]))",
     "legendFormat": "{{domain }} {{switch}}"
    }
   ]
  },
  {
   "title": "Memory cached",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by (domain, switch) (avg_over_time(ucs_mem_cached{domain=~\"${domain}\"}[10m]))",
     "legendFormat": "{{domain }} {{switch}}"
    }
   ]
  },
  { "title": "Memory errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Memory errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum by (domain, rack, chassis, blade) (ucs_address_parity_errors{domain=~\"${domain}\",chassis=~\"${chassis}\",rack=~\"${rack}\",blade=~\"${blade}\"})",
     "legendFormat": "{{domain}}  {{rack}} {{chassis}} {{blade}}"
    },
    {
     "expr": "sum by (domain, rack, chassis, blade) (ucs_ecc_singlebit_errors{domain=~\"${domain}\",chassis=~\"${chassis}\",rack=~\"${rack}\",blade=~\"${blade}\"})",
     "legendFormat": "{{domain}}  {{rack}} {{chassis}} {{blade}} ecc_singlebit_errors "
    },
    {
     "expr": "sum by (domain, rack, chassis, blade) (ucs_ecc_multibit_errors{domain=~\"${domain}\",chassis=~\"${chassis}\",rack=~\"${rack}\",blade=~\"${blade}\"})",
     "legendFormat": "{{domain}}  {{rack}} {{chassis}} {{blade}} ecc_multibit_errors"
    },
    {
     "expr": "sum by (domain, rack, chassis, blade) (ucs_mismatch_errors{domain=~\"${domain}\",chassis=~\"${chassis}\",rack=~\"${rack}\",blade=~\"${blade}\"})",
     "legendFormat": "{{domain}}  {{rack}} {{chassis}} {{blade}} mismatch_errors"
    },
    {
     "expr": "sum by (domain, rack, chassis, blade) (ucs_dram_write_data_correctable_crc_errors{domain=~\"${domain}\",chassis=~\"${chassis}\",rack=~\"${rack}\",blade=~\"${blade}\"})",
     "legendFormat": "{{domain}}  {{rack}} {{chassis}} {{blade}} dram_write_data_correctable_crc_errors"
    },
    {
     "expr": "sum by (domain, rack, chassis, blade) (ucs_dram_write_data_un_correctable_crc_errors{domain=~\"${domain}\",chassis=~\"${chassis}\",rack=~\"${rack}\",blade=~\"${blade}\"})",
     "legendFormat": "{{domain}}  {{rack}} {{chassis}} {{blade}} dram_write_data_un_correctable_crc_errors"
    }
   ]
  },
  { "title": "Power consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Input current (A)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "sum by (domain, chassis, blade) (ucs_compute_mb_input_current{domain=~\"${domain}\",chassis=~\"${chassis}\",rack=~\"${rack}\",blade=~\"${blade}\"})",
     "legendFormat": "{{domain}} {{chassis}} {{blade}}"
    }
   ]
  },
  {
   "title": "Power consumed (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "max by (domain, chassis) (max_over_time(ucs_compute_mb_consumed_power{domain=~\"${domain}\",chassis=~\"${chassis}\",blade=~\"${blade}\",rack=~\"${rack}\"}[10m]))",
     "legendFormat": "{{domain}} {{chassis}}"
    }
   ]
  }
 ]
}